// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfypycrqovozdegxcooz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeXB5Y3Jxb3ZvemRlZ3hjb296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODExMjUsImV4cCI6MjA3Mzk1NzEyNX0.W8mPFITuqU9bIXXso7c7Y_38zchoQMaQdeS903-7c9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});